name: Build debian package
on:
  workflow_dispatch
jobs:
  do-in-container:
    container: debian:sid
    steps:
      - name: demo
        run: |
          apt install lsb-release
          lsb_release
