name: Build debian package
on:
  workflow_dispatch
jobs:
  do-in-container:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: demo
        run: |
          apt-get update
          apt-get -y -qq --no-install-recommands install ninja-build gettext cmake unzip curl git file
          git clone https://github.com/neovim/neovim
          cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
          cpack --config build/CPackConfig.cmake -G DEB
          ls -l build
          ls -l build/bin
  action-in-container:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: install dependnecies and tools
        run: |
          apt-get update && apt-get -y -qq upgrade
          apt-get -y -qq --no-install-recommands install ninja-build gettext cmake unzip curl git file
      - name: get source using action
        uses: actions/checkout@v4
        with:
          repository: neovim/neovim
      - name: show content of pwd
        run: |
          pwd
          ls -la
