name: Build debian package
on:
  workflow_dispatch
jobs:
  do-in-container:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: demo
        run: |
          apt update
          apt -y install ninja-build gettext cmake unzip curl git
          git clone https://github.com/neovim/neovim
          cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
          cpack --config build/CPackConfig.cmake -G DEB
          ls -l build
          ls -l build/bin
